export const getInvalidDialogues = (techName: string, requested: number, max: number) => [
    `"Are you a time traveler? ${techName} has only existed for ${max} years, but you want ${requested}..."`,
    `"I think the recruiter skipped math class. Asking for ${requested} years on a ${max}-year-old tool is wild."`,
    `"Maybe they count overtime as double years? It's physically impossible otherwise."`,
    `"Error 404: Logic not found. ${techName} is younger than the experience required."`,
    `"Delusional level: Expert. Maximum possible is ${max} years."`,
    `"Sure, let me just invent a time machine real quick."`,
    `"Let me guess—this JD was written on a Friday at 4:59 PM."`,
    `"Love the confidence. Shame the math is completely fictional."`,
    `"I too enjoy science fiction job descriptions."`,
    `"Math? Never heard of her."`,
    `"Whoever wrote this believes time is a suggestion."`,
    `"Cool requirement. Completely detached from reality, but cool."`,
    `"This requirement is so unrealistic it should come with popcorn."`,
    `"Yes, I definitely remember working with ${techName} back in the Jurassic period."`,
    `"If experience could be downloaded, maybe… but no."`,
    `"Time traveler detected. ${techName} is only ${max} years old."`,
    `"Asking for ${requested} years on a ${max}-year-old tool. Math is hard."`,
    `"Recruiter logic: ${requested} > ${max}. Reality: No."`,
    `"Impossible. Unless they count overtime as double years."`,
    `"404: Logic not found. Tech released in ${new Date().getFullYear() - max}."`,
]

export const validDialogues = [
    `"Congrats, the math actually works."`,
    `"Shocking—no laws of physics were harmed."`,
    `"Finally, a requirement that won’t cause headaches."`,
    `"Someone used a calculator. Amazing."`,
    `"Recruiter can count. Plot twist of the year."`,
    `"Reasonable for once. Enjoy it."`,
    "Wild — a JD that lives in reality.",
    "Huh. Accuracy? Didn’t expect that here.",
    "Nice. No time travel required this time.",
    "Surprising. This one actually makes sense.",
    "Look at that — basic math in action.",
    "A rare sight: a realistic requirement.",
    "Nothing absurd here. Refreshing.",
    "Finally, something grounded in the real world.",
    "This one won’t make you question humanity.",
    "Shocker: the numbers don’t lie this time.",
    `"The math actually checks out."`,
    `"No laws of physics violated here."`,
    `"Finally, a realistic requirement."`,
    `"Recruiter used a calculator! It's super effective."`,
    "Safe. No time travel required.",
]
